### ISSUE TITLE
获取课表到获取考试信息后直接报错

### ISSUE THREAD

**Issue by jackyu0915** [miaotony/NUAA_ClassSchedule#14]
具体情况如下图
![bug](https://raw.githubusercontent.com/jackyu0915/img/master/img/bug.png)

**Comment by miaotony** [comment]
@jackyu0915  请问在您的教务系统里，考试信息是否为空？

**Comment by miaotony** [comment]
![图片](https://user-images.githubusercontent.com/41962043/70372437-090e5600-191a-11ea-88ff-5e29f9d3dee5.png)
https://github.com/miaotony/NUAA_ClassSchedule/blob/606557afe8ed02caa3daf53e3c66a8f72939d6e5/getClassSchedule.py#L262  

应该是这一句的问题。  
列表为空导致`list index out of range`.  
会尽快解决一下这个问题  
感谢反馈哈~

**Comment by miaotony** [comment]
不是上面的那个问题。。  
看了一下教务系统  
![图片](https://user-images.githubusercontent.com/41962043/70372883-838da480-191f-11ea-847d-6d9412266de8.png)
然后debug了一下，发现是之前这里的`时间未安排`考虑不周，在匹配的时候出了问题。  
具体来说是这一条语句的问题：  
https://github.com/miaotony/NUAA_ClassSchedule/blob/606557afe8ed02caa3daf53e3c66a8f72939d6e5/examObj.py#L22  

目前该问题已解决。   
![图片](https://user-images.githubusercontent.com/41962043/70372925-3fe76a80-1920-11ea-908a-28e6892f77f7.png)

感谢反馈呀~
