### ISSUE TITLE
登录时提示 **`ERROR! 请不要过快点击!`**  

### ISSUE THREAD

**Issue by miaotony** [miaotony/NUAA_ClassSchedule#2]
登录时提示 **`ERROR! 请不要过快点击!`**    
![图片](https://user-images.githubusercontent.com/41962043/67147657-5599c580-f2c9-11e9-9d5a-dd6ea7af9ff7.png)

**Comment by Villivateur** [comment]
爬的时候慢一点就好，好像一秒钟不超过两次

**Comment by miaotony** [comment]
> 
> 
> 爬的时候慢一点就好，好像一秒钟不超过两次

找到问题了emmm。原来登录的时候先GET获取token，加密之后直接就POST了，于是乎被服务器给判定为操作过快了。现在在POST之前加了个延时就没问题了。  

![解决方案](https://user-images.githubusercontent.com/41962043/68475251-9484c080-0262-11ea-9cb2-17134ccd9733.png)
