### ISSUE TITLE
教务系统登录方式调整导致无法登录

### ISSUE THREAD

**Issue by BiffDx** [miaotony/NUAA_ClassSchedule#30]
教务系统从2023年1月5日起[调整了登录方式](https://aao.nuaa.edu.cn/2022/1227/c8230a301457/page.htm)，选择系统独立入口登录需要进行密码和手机验证码双重验证，导致在控制台输入学号、密码及验证码后无法正常登录。

**Comment by miaotony** [comment]
唔，看了下确实加了个手机验证码
不过咱账号已经被禁用登不上了，没办法调试了（
您可以自己改改代码加一下这部分，欢迎 PR！

**Comment by Jonny-Wongg** [comment]
（不太会美化代码，见谅~）
尝试修改了一下，应该能用了：
在“getClassSchedule.py”的aao_login()，对密码加密后，添加下列代码（原有的postData需要添加一个captcha_phone字段）：

        postData = {'captcha': captcha_str, 'username': stuID, 'password': postPwd}
        time.sleep(random.uniform(0.7, 1))  # 更改为随机延时
        r2 = session.post(host + '/eams/login!sendPhoneCaptcha.action',
                          data=postData, timeout=10)

        print("请等待短信验证码，亦或在微信我的消息栏目中的验证码，并输入：")
        apctchaphone=input()

        # 开始登录啦
        postData = {'ekingstar':2,'username': stuID, 'password': postPwd,
                    'captcha_response': captcha_str,'captcha_phone':apctchaphone}

**Comment by Jonny-W12138** [comment]
（不太会美化代码，见谅~）
尝试修改了一下，应该能用了：
在“getClassSchedule.py”的aao_login()，对密码加密后，添加下列代码（原有的postData需要添加一个captcha_phone字段）：

        postData = {'captcha': captcha_str, 'username': stuID, 'password': postPwd}
        time.sleep(random.uniform(0.7, 1))  # 更改为随机延时
        r2 = session.post(host + '/eams/login!sendPhoneCaptcha.action',
                          data=postData, timeout=10)

        print("请等待短信验证码，亦或在微信我的消息栏目中的验证码，并输入：")
        apctchaphone=input()

        # 开始登录啦
        postData = {'ekingstar':2,'username': stuID, 'password': postPwd,
                    'captcha_response': captcha_str,'captcha_phone':apctchaphone}

**Comment by miaotony** [comment]
> （不太会美化代码，见谅~） 尝试修改了一下，应该能用了： 在“getClassSchedule.py”的aao_login()，对密码加密后，添加下列代码（原有的postData需要添加一个captcha_phone字段）：
> 
> ```
>     postData = {'captcha': captcha_str, 'username': stuID, 'password': postPwd}
>     time.sleep(random.uniform(0.7, 1))  # 更改为随机延时
>     r2 = session.post(host + '/eams/login!sendPhoneCaptcha.action',
>                       data=postData, timeout=10)
> 
>     print("请等待短信验证码，亦或在微信我的消息栏目中的验证码，并输入：")
>     apctchaphone=input()
> 
>     # 开始登录啦
>     postData = {'ekingstar':2,'username': stuID, 'password': postPwd,
>                 'captcha_response': captcha_str,'captcha_phone':apctchaphone}
> ```

好耶，谢谢哈！  

顺便想问一下这个代码可以成功运行么？我这边没账号没法测试了（

方便的话可以直接提个 PR 捏~

**Comment by miaotony** [comment]
Fixed in V0.25.0.20230807.
