### ISSUE TITLE
重复点击.ics文件，win日历生成重复日程，无法快速删除

### ISSUE THREAD

**Issue by Hunmble-bird** [miaotony/NUAA_ClassSchedule#31]
这个.ics文件我就想先预览看看，一点击.ics就把日程加载到微软日历中。
因为不知名原因我又点了一遍，现在每节课都有两个日程。
而且没办法批量删除。
有没有可能实现脚本一键清除说有日程啊
求求大佬

**Comment by miaotony** [comment]
建议每次新建一个日历，出错的话删除日历就好了

![图片](https://user-images.githubusercontent.com/41962043/225490594-ce407099-e644-4d8e-858b-4825ee03b67a.png)

**Comment by Hunmble-bird** [comment]
貌似ios outlook 软件与win11自带日历程序没有新建日历选项，但是outlook网页版一定存在新建日历选项
